language: node_js
node_js: stable
cache:
  directories:
    - node_modules

before_install:
  - npm install cnpm -g

# S: Build Lifecycle
install:
  - cnpm install
  - cd ./demo && cnpm install

before_script:
  - cd ..

script:
  - npm run build && cp -f ./dist/CaptureColor.umd.js ./demo/src/static
  - cd ./demo && npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "palmerye"
  - git config user.email "palmerye@gmail.com"
  - git add .
  - git commit -m ":memo:\ Update docs by CI"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" gh-pages:gh-pages
  - cd ../../
  - git init
  - git config user.name "palmerye"
  - git config user.email "palmerye@gmail.com"
  - git add .
  - git commit -m ":memo:\ Update docs by CI"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/palmerye/CaptureColor.git